#!/bin/bash
for i in {1..5}; do
    echo $i
    if [ $i -eq 3 ]; then
        break
    fi
done
echo "For loop terminated"

we are adding new line we hookes

one more line from linux

mahadev

lastest commit for check poll scm

shivaram


